# Generated by Django 4.2.16 on 2026-07-11 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('agencies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('RECRUITMENT_OPEN', 'Recruitment Open'), ('RECRUITMENT_CLOSED', 'Recruitment Closed'), ('DEADLINE_EXTENDED', 'Deadline Extended'), ('SHORTLIST_PUBLISHED', 'Shortlist Published'), ('PORTAL_DOWN', 'Portal Down'), ('PORTAL_UP', 'Portal Up'), ('FAKE_PORTAL_DETECTED', 'Fake Portal Detected'), ('BROADCAST', 'Admin Broadcast'), ('OTHER', 'Other Update')], db_index=True, default='RECRUITMENT_OPEN', max_length=30)),
                ('title', models.CharField(help_text="Alert headline e.g. 'NCS 2025 Recruitment Portal Now Open'", max_length=500)),
                ('positions', models.TextField(blank=True, default='', help_text='Extracted positions/roles from the page.')),
                ('deadline', models.CharField(blank=True, default='', help_text="Extracted deadline string e.g. '28 February 2025'", max_length=100)),
                ('requirements', models.TextField(blank=True, default='', help_text='Extracted requirements (WAEC, SSCE, degree level, etc.)')),
                ('source_url', models.URLField(help_text='URL where the recruitment was detected.', max_length=500)),
                ('content_excerpt', models.TextField(blank=True, default='', help_text='First 2000 characters of the page content at time of detection.')),
                ('trust_score', models.IntegerField(default=0, help_text='Trust score 0–100. Computed by the fake detection engine.')),
                ('ai_classification', models.CharField(blank=True, default='', help_text='Gemini AI result: REAL | FAKE | UNCERTAIN', max_length=20)),
                ('ai_confidence', models.IntegerField(default=0, help_text='Gemini AI confidence 0–100.')),
                ('ai_red_flags', models.JSONField(blank=True, default=list, help_text='List of red flags identified by Gemini AI.')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Admin Review'), ('APPROVED', 'Approved — Sent to Users'), ('REJECTED', 'Rejected — Marked Fake'), ('HELD', 'Held for Admin Review')], db_index=True, default='PENDING', max_length=20)),
                ('is_verified', models.BooleanField(default=False, help_text='Manually verified as real by an admin.')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, default='')),
                ('recipients_count', models.PositiveIntegerField(default=0, help_text='Number of users this alert was sent to.')),
                ('sent_at', models.DateTimeField(blank=True, help_text='When dispatch began.', null=True)),
                ('report_count', models.PositiveIntegerField(default=0, help_text='Number of user fake reports on this alert.')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='agencies.agency')),
                ('portal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='agencies.portal')),
                ('verified_by', models.ForeignKey(blank=True, help_text='Django admin user who verified this alert.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alert',
                'verbose_name_plural': 'Alerts',
                'db_table': 'alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('SAVED', 'Saved'), ('REPORTED', 'Reported as Fake'), ('SHARED', 'Shared')], max_length=20)),
                ('report_reason', models.CharField(blank=True, default='', help_text='Reason given when action_type = REPORTED.', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='alerts.alert')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_actions', to='accounts.telegramuser')),
            ],
            options={
                'verbose_name': 'Alert Action',
                'verbose_name_plural': 'Alert Actions',
                'db_table': 'alert_actions',
                'unique_together': {('user', 'alert', 'action_type')},
            },
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['agency', 'created_at'], name='idx_alerts_agency_date'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['event_type', 'status'], name='idx_alerts_type_status'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['trust_score'], name='idx_alerts_trust'),
        ),
    ]
