# Generated by Django 4.2.16 on 2026-07-11 13:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0002_alter_portal_status'),
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitmentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(help_text='Unique event code, e.g. evt_20260711_000412', max_length=50, unique=True)),
                ('event_type', models.CharField(choices=[('RECRUITMENT_OPEN', 'Recruitment Open'), ('RECRUITMENT_CLOSED', 'Recruitment Closed'), ('DEADLINE_EXTENDED', 'Deadline Extended'), ('SHORTLIST_PUBLISHED', 'Shortlist Published'), ('PORTAL_DOWN', 'Portal Down'), ('PORTAL_UP', 'Portal Up'), ('FAKE_PORTAL_DETECTED', 'Fake Portal Detected'), ('BROADCAST', 'Admin Broadcast'), ('OTHER', 'Other Update')], default='RECRUITMENT_OPEN', max_length=30)),
                ('content_hash', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('portal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='agencies.portal')),
            ],
            options={
                'db_table': 'recruitment_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DecisionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_matches', models.JSONField(blank=True, default=list, help_text='List of rules matched during classification.')),
                ('gemini_score', models.FloatField(default=0.0, help_text='Gemini confidence score (0.0 to 1.0)')),
                ('final_trust', models.IntegerField(default=0, help_text='Calculated trust score (0 to 100)')),
                ('reason', models.TextField(blank=True, default='', help_text='Human readable summary of the decision.')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='decision_log', to='alerts.recruitmentevent')),
            ],
            options={
                'db_table': 'decision_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='alert',
            name='recruitment_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='alerts.recruitmentevent'),
        ),
    ]
