# Generated by Django 4.2.16 on 2026-07-19 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_add_fingerprint_deduplication'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['status', 'created_at'], name='idx_alerts_status_date'),
        ),
    ]
