# Generated by Django 4.2.16 on 2026-07-19 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alerts', '0004_add_status_date_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='trust_score_overridden_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='trust_score_overridden_by',
            field=models.ForeignKey(blank=True, help_text='Django staff user who manually override the trust score.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trust_score_overridden_alerts', to=settings.AUTH_USER_MODEL),
        ),
    ]
