# Generated by Django 4.2.16 on 2026-07-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0005_add_trust_score_override_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitmentevent',
            name='fingerprint',
            field=models.CharField(
                max_length=64,
                db_index=True,
                help_text='SHA-256 fingerprint of the recruitment identity. Multiple events may share it as an update chain.',
            ),
        ),
    ]
