# Generated by Django 4.2.16 on 2026-07-23 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0006_allow_event_update_chains'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Admin Review'), ('APPROVED', 'Approved — Sent to Users'), ('REJECTED', 'Rejected — Marked Fake'), ('HELD', 'Held for Admin Review'), ('SUPERSEDED', 'Superseded by Update')], db_index=True, default='PENDING', max_length=20),
        ),
    ]
