# Generated by Django 4.2.16 on 2026-07-25 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0007_alter_alert_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('excerpt', models.TextField(blank=True, default='')),
                ('content', models.TextField(help_text='Markdown format content.')),
                ('category', models.CharField(default='Scam Prevention', max_length=100)),
                ('author', models.CharField(default='Shamsuddeen Yusuf', max_length=100)),
                ('read_time', models.CharField(default='5 min read', max_length=50)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'db_table': 'blog_posts',
                'ordering': ['-created_at'],
            },
        ),
    ]
