# Generated by Django 4.2.16 on 2026-07-25 20:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0006_alter_portal_health_status_alter_portal_status'),
        ('alerts', '0008_blogpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='RejectedDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=500)),
                ('deadline', models.CharField(blank=True, default='', max_length=100)),
                ('positions', models.TextField(blank=True, default='')),
                ('status', models.CharField(db_index=True, default='AUTO REJECTED STALE DEADLINE', help_text='Rejection status e.g. AUTO REJECTED STALE DEADLINE', max_length=50)),
                ('reason', models.TextField(help_text='Detailed reason for automatic rejection.')),
                ('raw_content_excerpt', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rejected_detections', to='agencies.agency')),
                ('portal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rejected_detections', to='agencies.portal')),
            ],
            options={
                'verbose_name': 'Rejected Detection',
                'verbose_name_plural': 'Rejected Detections',
                'db_table': 'rejected_detections',
                'ordering': ['-created_at'],
            },
        ),
    ]
