# Generated by Django 4.2.16 on 2026-07-29 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0009_rejecteddetection'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='decision_source',
            field=models.CharField(choices=[('AUTO', 'Automated'), ('HUMAN', 'Manual Review')], default='HUMAN', help_text='Distinguishes automated decision (AUTO) from manual admin decision (HUMAN)', max_length=20),
        ),
        migrations.AddField(
            model_name='alert',
            name='trust_category',
            field=models.CharField(blank=True, choices=[('VERIFIED', 'Verified Official'), ('LIKELY', 'Likely Official'), ('UNCONFIRMED', 'Unconfirmed'), ('SUSPICIOUS', 'Suspicious/Fake')], help_text='Automated classification tier: VERIFIED (90-100), LIKELY (70-89), UNCONFIRMED (50-69), SUSPICIOUS (0-49)', max_length=20, null=True),
        ),
    ]
