# Generated by Django 4.2.16 on 2026-07-29 13:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0010_alert_decision_source_alert_trust_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-published_date', '-created_at'], 'verbose_name': 'Blog Post', 'verbose_name_plural': 'Blog Posts'},
        ),
        migrations.AddField(
            model_name='blogpost',
            name='body',
            field=models.TextField(blank=True, default='', help_text='Body content (Markdown or HTML format).'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='meta_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='published_date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='reading_time',
            field=models.PositiveIntegerField(default=1, help_text='Reading time in minutes'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('recruitment', 'Recruitment Guides'), ('tech', 'Tech Guides')], db_index=True, default='recruitment', max_length=50),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.TextField(blank=True, default='', help_text='Markdown format content.'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique=True),
        ),
    ]
