# Generated by Django 4.2.16 on 2026-07-11 12:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('telegram_id', models.BigIntegerField(help_text='Telegram user ID — permanent, unique per user.', primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, default='', max_length=100)),
                ('username', models.CharField(blank=True, help_text='Telegram @username, nullable (not all users set one).', max_length=100, null=True)),
                ('state', models.CharField(choices=[('NEW_USER', 'New User'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('PREMIUM', 'Premium'), ('BANNED', 'Banned')], db_index=True, default='NEW_USER', max_length=20)),
                ('is_admin', models.BooleanField(default=False, help_text='Has access to /admin bot commands.')),
                ('is_super_admin', models.BooleanField(default=False, help_text='Has access to /broadcast and destructive admin commands.')),
                ('timezone', models.CharField(default='Africa/Lagos', help_text="User's preferred timezone for alert times.", max_length=50)),
                ('language', models.CharField(default='en', help_text='Bot language preference (en / ha).', max_length=10)),
                ('receive_alerts', models.BooleanField(default=True, help_text='Master switch — False means user has /unsubscribed.')),
                ('notification_frequency', models.CharField(choices=[('instant', 'Instant'), ('daily', 'Daily Digest')], default='instant', max_length=20)),
                ('is_premium', models.BooleanField(default=False)),
                ('premium_expires', models.DateTimeField(blank=True, null=True)),
                ('consented_to_data_policy', models.BooleanField(default=False, help_text='NDPR: User tapped [I Agree] on /start.')),
                ('consent_given_at', models.DateTimeField(blank=True, null=True)),
                ('alerts_received', models.PositiveIntegerField(default=0, help_text='Total alerts delivered to this user (denormalised for performance).')),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When user first sent /start.')),
                ('last_active_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp of their last bot interaction.')),
            ],
            options={
                'verbose_name': 'Telegram User',
                'verbose_name_plural': 'Telegram Users',
                'db_table': 'users',
                'ordering': ['-joined_at'],
                'indexes': [models.Index(fields=['state'], name='idx_users_state'), models.Index(fields=['is_admin'], name='idx_users_admin'), models.Index(fields=['joined_at'], name='idx_users_joined')],
            },
        ),
    ]
