# Generated by Django 4.2.16 on 2026-07-18 21:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alerts', '0003_add_fingerprint_deduplication'),
        ('accounts', '0002_create_superuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('categories_of_interest', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('saved_jobs', models.ManyToManyField(blank=True, related_name='saved_by_users', to='alerts.alert')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='web_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Web User Profile',
                'verbose_name_plural': 'Web User Profiles',
                'db_table': 'web_users',
            },
        ),
    ]
