# Generated by Django 4.2.16 on 2026-07-26 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_webuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='webuser',
            name='auth_provider',
            field=models.CharField(default='email', help_text="Authentication provider, e.g. 'email', 'google'.", max_length=20),
        ),
        migrations.AddField(
            model_name='webuser',
            name='google_sub',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Google user ID (sub).', max_length=255),
        ),
    ]
