# Generated by Django 4.2.16 on 2026-07-11 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('agencies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FakeDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(help_text="Root domain e.g. 'customs-recruitment-2025.com'", max_length=255, unique=True)),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('confirmed_by_admin', models.BooleanField(default=False, help_text='Admin has manually confirmed this is fake.')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('report_count', models.PositiveIntegerField(default=0, help_text='Number of user reports that flagged this domain.')),
                ('notes', models.TextField(blank=True, default='')),
                ('agency', models.ForeignKey(blank=True, help_text='Agency this domain was pretending to be.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fake_domains', to='agencies.agency')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_fake_domains', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fake Domain',
                'verbose_name_plural': 'Fake Domains',
                'db_table': 'fake_domains',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('PAYMENT', 'It asked me to pay'), ('WRONG_URL', 'Wrong or unofficial website'), ('NOT_OFFICIAL', 'Not from the official agency source'), ('SUSPICIOUS', 'Content looks suspicious'), ('OTHER', 'Other reason')], default='OTHER', max_length=20)),
                ('notes', models.CharField(blank=True, default='', max_length=500)),
                ('reviewed', models.BooleanField(default=False)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='alerts.alert')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_submitted', to='accounts.telegramuser')),
            ],
            options={
                'verbose_name': 'Alert Report',
                'verbose_name_plural': 'Alert Reports',
                'db_table': 'alert_reports',
                'ordering': ['-created_at'],
                'unique_together': {('alert', 'user')},
            },
        ),
    ]
