# Generated by Django 4.2.16 on 2026-07-11 12:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('agencies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='False = user unsubscribed from this specific agency.')),
                ('subscribed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('unsubscribed_at', models.DateTimeField(blank=True, help_text='Timestamp when user last unsubscribed from this agency.', null=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='agencies.agency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='accounts.telegramuser')),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'db_table': 'subscriptions',
                'ordering': ['agency__acronym'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='idx_subs_user_active'), models.Index(fields=['agency', 'is_active'], name='idx_subs_agency_active')],
                'unique_together': {('user', 'agency')},
            },
        ),
    ]
