# Generated by Django 4.2.16 on 2026-07-20 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('query_text', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_matched_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Keyword Subscription',
                'verbose_name_plural': 'Keyword Subscriptions',
                'db_table': 'keyword_subscriptions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'is_active'], name='idx_kw_sub_email_active'), models.Index(fields=['is_active'], name='idx_kw_sub_active')],
            },
        ),
    ]
