# Generated by Django 4.2.16 on 2026-07-20 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0005_add_trust_score_override_fields'),
        ('accounts', '0003_webuser'),
        ('subscriptions', '0002_keywordsubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramJobWatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_notified_at', models.DateTimeField(blank=True, null=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchers', to='alerts.alert')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watched_jobs', to='accounts.telegramuser')),
            ],
            options={
                'verbose_name': 'Telegram Job Watch',
                'verbose_name_plural': 'Telegram Job Watches',
                'db_table': 'telegram_job_watches',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='idx_jw_user_active'), models.Index(fields=['alert', 'is_active'], name='idx_jw_alert_active')],
                'unique_together': {('user', 'alert')},
            },
        ),
    ]
