# Generated by Django 4.2.16 on 2026-07-11 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('acronym', models.CharField(help_text='Short code e.g. NNPC, NCS, EFCC.', max_length=20, unique=True)),
                ('official_domains', models.JSONField(default=list, help_text='List of whitelisted official domains e.g. ["customs.gov.ng"]')),
                ('logo_url', models.URLField(blank=True, default='', help_text='URL to agency logo image for use in alert messages.')),
                ('category', models.CharField(choices=[('SECURITY', 'Security & Law Enforcement'), ('FINANCE', 'Finance & Revenue'), ('UTILITIES', 'Utilities & Energy'), ('HEALTH', 'Health & Pharmaceuticals'), ('EDUCATION', 'Education & Research'), ('TRANSPORT', 'Transport & Aviation'), ('STATISTICS', 'Statistics & Data'), ('JUDICIARY', 'Judiciary & Legal'), ('OTHER', 'Other')], db_index=True, default='OTHER', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this agency is currently being monitored.')),
                ('description', models.TextField(blank=True, default='', help_text='Brief description of the agency for /agencies command.')),
                ('subscriber_count', models.PositiveIntegerField(default=0, help_text='Cached count of active subscribers (updated by signal).')),
                ('total_alerts_sent', models.PositiveIntegerField(default=0, help_text='Total alerts ever dispatched from this agency.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Agency',
                'verbose_name_plural': 'Agencies',
                'db_table': 'agencies',
                'ordering': ['acronym'],
            },
        ),
        migrations.CreateModel(
            name='Portal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Human-readable name e.g. 'NCS Recruitment Portal'", max_length=200)),
                ('url', models.URLField(help_text='The URL to scrape.', max_length=500)),
                ('scrape_method', models.CharField(choices=[('HTTP', 'Simple HTTP (BeautifulSoup)'), ('PLAYWRIGHT', 'Headless Browser (Playwright)'), ('PDF', 'PDF Parser')], default='HTTP', max_length=20)),
                ('check_interval_minutes', models.PositiveIntegerField(default=15, help_text='How often to check this portal (minutes). Default: 15.')),
                ('is_active', models.BooleanField(default=True, help_text='Set to False to pause monitoring without deleting.')),
                ('status', models.CharField(choices=[('UP', 'Up'), ('DOWN', 'Down'), ('UNKNOWN', 'Unknown'), ('PAUSED', 'Paused (maintenance)')], db_index=True, default='UNKNOWN', max_length=10)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_successful_check_at', models.DateTimeField(blank=True, null=True)),
                ('last_change_detected_at', models.DateTimeField(blank=True, null=True)),
                ('consecutive_failures', models.PositiveIntegerField(default=0, help_text='Number of consecutive failed checks. Resets on success.')),
                ('uptime_percentage', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('notes', models.TextField(blank=True, default='', help_text='Internal admin notes about this portal.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portals', to='agencies.agency')),
            ],
            options={
                'verbose_name': 'Portal',
                'verbose_name_plural': 'Portals',
                'db_table': 'portals',
                'ordering': ['agency__acronym', 'name'],
                'indexes': [models.Index(fields=['is_active', 'status'], name='idx_portals_active_status'), models.Index(fields=['agency', 'is_active'], name='idx_portals_agency_active')],
            },
        ),
    ]
