# Generated by Django 4.2.16 on 2026-07-11 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portal',
            name='status',
            field=models.CharField(choices=[('ONLINE', 'Online / Up'), ('OFFLINE', 'Offline'), ('BLOCKED', 'Blocked by Firewall/Cloudflare'), ('CAPTCHA', 'Captcha Challenge Detected'), ('MAINTENANCE', 'Under Maintenance'), ('CHANGED_LAYOUT', 'Changed Layout'), ('RATE_LIMITED', 'Rate Limited'), ('UNKNOWN', 'Unknown'), ('UP', 'Up (Deprecated)'), ('DOWN', 'Down (Deprecated)'), ('PAUSED', 'Paused (Deprecated)')], db_index=True, default='UNKNOWN', max_length=30),
        ),
    ]
