# Generated by Django 4.2.16 on 2026-07-11 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0002_alter_portal_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='portal',
            name='confidence',
            field=models.PositiveIntegerField(default=100, help_text='Scraping reliability score (0-100). Decreases on failures.'),
        ),
        migrations.AddField(
            model_name='portal',
            name='country',
            field=models.CharField(default='NG', help_text='Country code (NG=Nigeria, GH=Ghana, etc.)', max_length=2),
        ),
        migrations.AddField(
            model_name='portal',
            name='health_status',
            field=models.CharField(choices=[('ONLINE', 'Online / Healthy'), ('OFFLINE', 'Offline'), ('BLOCKED', 'Blocked by Firewall/Cloudflare'), ('CAPTCHA', 'Captcha Challenge Detected'), ('RATE_LIMITED', 'Rate Limited'), ('MAINTENANCE', 'Under Maintenance'), ('UNKNOWN', 'Unknown')], db_index=True, default='UNKNOWN', help_text='Current health status of the portal.', max_length=30),
        ),
        migrations.AddField(
            model_name='portal',
            name='poll_interval',
            field=models.PositiveIntegerField(default=900, help_text='How often to check this portal (seconds). 300=5min, 900=15min, 1800=30min, 3600=60min.'),
        ),
        migrations.AddField(
            model_name='portal',
            name='priority',
            field=models.CharField(choices=[('HIGH', 'High Priority (5 min)'), ('MEDIUM', 'Medium Priority (20 min)'), ('LOW', 'Low Priority (60 min)')], db_index=True, default='MEDIUM', help_text='Portal priority: HIGH (5 min), MEDIUM (20 min), LOW (60 min).', max_length=10),
        ),
        migrations.AddField(
            model_name='portal',
            name='response_time_ms',
            field=models.PositiveIntegerField(blank=True, help_text='Last recorded response time in milliseconds.', null=True),
        ),
        migrations.AddField(
            model_name='portal',
            name='tags',
            field=models.JSONField(default=list, help_text="List of tags/categories: ['Security', 'Finance', 'Education', etc.]"),
        ),
        migrations.AlterField(
            model_name='portal',
            name='check_interval_minutes',
            field=models.PositiveIntegerField(default=15, help_text='Legacy field. Use poll_interval instead (in seconds).'),
        ),
        migrations.AlterField(
            model_name='portal',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Set to False to pause monitoring without deleting.'),
        ),
        migrations.AlterField(
            model_name='portal',
            name='scrape_method',
            field=models.CharField(choices=[('REQUESTS', 'HTTP Requests (BeautifulSoup)'), ('PLAYWRIGHT', 'Headless Browser (Playwright)'), ('PDF', 'PDF Parser'), ('RSS', 'RSS Feed'), ('API', 'REST API')], default='REQUESTS', max_length=20),
        ),
        migrations.AlterField(
            model_name='portal',
            name='status',
            field=models.CharField(choices=[('ONLINE', 'Online / Up'), ('OFFLINE', 'Offline'), ('BLOCKED', 'Blocked by Firewall/Cloudflare'), ('CAPTCHA', 'Captcha Challenge Detected'), ('MAINTENANCE', 'Under Maintenance'), ('CHANGED_LAYOUT', 'Changed Layout'), ('RATE_LIMITED', 'Rate Limited'), ('UNKNOWN', 'Unknown'), ('UP', 'Up (Deprecated)'), ('DOWN', 'Down (Deprecated)'), ('PAUSED', 'Paused (Deprecated)')], db_index=True, default='UNKNOWN', help_text='Deprecated. Use health_status instead.', max_length=30),
        ),
    ]
