# Generated by Django 4.2.16 on 2026-07-15 — manually edited to add data migration
# for slug population before the unique constraint is applied.

from django.db import migrations, models
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    """Populate slug for all existing Agency rows from their acronym."""
    Agency = apps.get_model('agencies', 'Agency')
    seen = set()
    for agency in Agency.objects.all():
        base = slugify(agency.acronym)
        slug = base
        counter = 1
        while slug in seen:
            slug = f"{base}-{counter}"
            counter += 1
        seen.add(slug)
        agency.slug = slug
        agency.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0003_portal_confidence_portal_country_and_more'),
    ]

    operations = [
        # Step 1: add non-unique, nullable slug column first as CharField (no index)
        migrations.AddField(
            model_name='agency',
            name='slug',
            field=models.CharField(
                max_length=30, blank=True, default='',
                help_text="URL-safe identifier, auto-generated from acronym. e.g. 'nnpc', 'ncs'.",
            ),
        ),
        # Step 2: populate slugs from existing acronyms
        migrations.RunPython(populate_slugs, reverse_code=migrations.RunPython.noop),
        # Step 3: make slug unique now that all rows have values
        migrations.AlterField(
            model_name='agency',
            name='slug',
            field=models.SlugField(
                max_length=30, unique=True, blank=True,
                help_text="URL-safe identifier, auto-generated from acronym. e.g. 'nnpc', 'ncs'.",
            ),
        ),
        # Other new fields
        migrations.AddField(
            model_name='agency',
            name='avg_confidence_score',
            field=models.FloatField(default=0.0, help_text='Average AI confidence score across all alerts from this agency.'),
        ),
        migrations.AddField(
            model_name='agency',
            name='false_positives',
            field=models.PositiveIntegerField(default=0, help_text='Count of confirmed false-positive alerts from this agency.'),
        ),
        migrations.AddField(
            model_name='agency',
            name='scam_domains_blocked',
            field=models.PositiveIntegerField(default=0, help_text='Count of scam domains blocked for this agency.'),
        ),
        migrations.AddField(
            model_name='agency',
            name='vetted_score',
            field=models.PositiveIntegerField(default=85, help_text='Agency vetting score 0-100. Manual admin field.'),
        ),
        migrations.AddField(
            model_name='portal',
            name='location_state',
            field=models.CharField(blank=True, default='Federal', help_text="Primary location/state for this portal's listings.", max_length=50),
        ),
    ]
