# Generated by Django 4.2.16 on 2026-07-19 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0004_add_agency_slug_vetted_score_portal_location'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='portal',
            index=models.Index(fields=['is_active', 'priority'], name='idx_portals_active_priority'),
        ),
    ]
