# Generated by Django 4.2.16 on 2026-07-25 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0005_add_portal_priority_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portal',
            name='health_status',
            field=models.CharField(choices=[('ONLINE', 'Online / Healthy'), ('OFFLINE', 'Offline'), ('BLOCKED', 'Blocked by Firewall/Cloudflare'), ('CAPTCHA', 'Captcha Challenge Detected'), ('CAPTCHA_PROTECTED', 'Captcha Protected'), ('RATE_LIMITED', 'Rate Limited'), ('MAINTENANCE', 'Under Maintenance'), ('DEGRADED', 'Degraded'), ('MANUAL_MONITORING_REQUIRED', 'Manual Monitoring Required'), ('UNKNOWN', 'Unknown')], db_index=True, default='UNKNOWN', help_text='Current health status of the portal.', max_length=30),
        ),
        migrations.AlterField(
            model_name='portal',
            name='status',
            field=models.CharField(choices=[('ONLINE', 'Online / Up'), ('OFFLINE', 'Offline'), ('BLOCKED', 'Blocked by Firewall/Cloudflare'), ('CAPTCHA', 'Captcha Challenge Detected'), ('CAPTCHA_PROTECTED', 'Captcha Protected'), ('MAINTENANCE', 'Under Maintenance'), ('CHANGED_LAYOUT', 'Changed Layout'), ('RATE_LIMITED', 'Rate Limited'), ('DEGRADED', 'Degraded'), ('MANUAL_MONITORING_REQUIRED', 'Manual Monitoring Required'), ('UNKNOWN', 'Unknown'), ('UP', 'Up (Deprecated)'), ('DOWN', 'Down (Deprecated)'), ('PAUSED', 'Paused (Deprecated)')], db_index=True, default='UNKNOWN', help_text='Deprecated. Use health_status instead.', max_length=30),
        ),
    ]
