# Generated by Django 4.2.16 on 2026-07-11 12:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agencies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_hash', models.CharField(help_text='MD5 hash of normalised page content.', max_length=32)),
                ('raw_content', models.TextField(blank=True, default='', help_text='Normalised page text at time of snapshot.')),
                ('status_code', models.IntegerField(blank=True, help_text='HTTP status code of the response.', null=True)),
                ('response_time_ms', models.IntegerField(blank=True, help_text='How long the request took in milliseconds.', null=True)),
                ('scrape_method_used', models.CharField(blank=True, default='', max_length=20)),
                ('has_change', models.BooleanField(default=False, help_text='True if this snapshot differs from the previous one.')),
                ('triggered_alert', models.BooleanField(default=False, help_text='True if this snapshot triggered an alert.')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('portal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='agencies.portal')),
            ],
            options={
                'verbose_name': 'Snapshot',
                'verbose_name_plural': 'Snapshots',
                'db_table': 'snapshots',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['portal', 'created_at'], name='idx_snapshots_portal_date'), models.Index(fields=['content_hash'], name='idx_snapshots_hash')],
            },
        ),
        migrations.CreateModel(
            name='PortalHealthLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('checks_total', models.PositiveIntegerField(default=0)),
                ('checks_successful', models.PositiveIntegerField(default=0)),
                ('checks_failed', models.PositiveIntegerField(default=0)),
                ('avg_response_time_ms', models.IntegerField(blank=True, null=True)),
                ('uptime_percentage', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('changes_detected', models.PositiveIntegerField(default=0)),
                ('alerts_triggered', models.PositiveIntegerField(default=0)),
                ('portal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_logs', to='agencies.portal')),
            ],
            options={
                'verbose_name': 'Portal Health Log',
                'verbose_name_plural': 'Portal Health Logs',
                'db_table': 'portal_health_logs',
                'ordering': ['-date'],
                'unique_together': {('portal', 'date')},
            },
        ),
    ]
