# Generated by Django 4.2.16 on 2026-07-11 12:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('SENT', 'Sent Successfully'), ('FAILED', 'Failed to Deliver'), ('BLOCKED', 'User Blocked Bot')], db_index=True, default='QUEUED', max_length=10)),
                ('telegram_message_id', models.BigIntegerField(blank=True, help_text='Telegram message ID returned by sendMessage API.', null=True)),
                ('error_message', models.TextField(blank=True, default='', help_text='Error details if status = FAILED.')),
                ('queued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('alert', models.ForeignKey(blank=True, help_text='Null for broadcast messages not tied to a specific alert.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='alerts.alert')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.telegramuser')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
                'ordering': ['-queued_at'],
                'indexes': [models.Index(fields=['status', 'queued_at'], name='idx_notif_status_queued'), models.Index(fields=['user', 'alert'], name='idx_notif_user_alert')],
                'unique_together': {('user', 'alert')},
            },
        ),
    ]
