# Generated by Django 4.2.16 on 2026-07-29 15:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_webuser_auth_provider_webuser_google_sub'),
        ('alerts', '0011_alter_blogpost_options_blogpost_body_and_more'),
        ('notifications', '0002_pushsubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('notification_type', models.CharField(choices=[('NEW_JOB', 'New Recruitment'), ('STATUS_CHANGE', 'Status Update'), ('DEADLINE_WARNING', 'Deadline Approaching'), ('BROADCAST', 'Official Broadcast')], default='NEW_JOB', max_length=30)),
                ('target_url', models.CharField(blank=True, default='', max_length=500)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dashboard_notifications', to='alerts.recruitmentevent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_notifications', to='accounts.webuser')),
            ],
            options={
                'verbose_name': 'Web Notification',
                'verbose_name_plural': 'Web Notifications',
                'db_table': 'web_notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
